- name: update apt package cache
  apt: update_cache=yes
  when: ansible_os_family == "Debian"

- name: install epel-repo rpm
  yum: name=epel-release state=installed
  when: ansible_os_family == 'RedHat'
  
- name: Install libselinux-python
  yum: name=libselinux-python state=latest
  when: ansible_os_family == 'RedHat'

- name: install common packages debian/ubuntu
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - git
  when: ansible_os_family == "Debian"

- name: install git redhat/centos
  yum: name=git state=latest
  when: ansible_os_family == "RedHat"


- name: install development tools redhat/centos
  yum: name='@Development tools' state=present
  when: ansible_os_family == "RedHat"
